name: test
on:
  push:
    branches:
    - main
  

jobs:

  test_win_x64:
    runs-on: windows-latest
    steps:
    - name: Display the path
      run: echo ${env:PATH}
      shell: pwsh
    - name: Choco adk
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install windows-adk-all
    - name: Choco adk
      uses: crazy-max/ghaction-chocolatey@v2
      with:
        args: install mdt
        